---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bitmain.
--- DateTime: 2018/5/31 下午4:40
---


wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json;charset=utf-8"

---  随机交换顺序
function shuffle(paths)
    local j, k
    local n = #paths
    for i = 1, n do
        j, k = math.random(n), math.random(n)
        paths[j], paths[k] = paths[k], paths[j]
    end
    return paths
end

function non_empty_lines_from(file)
    --  if not file_exists(file) then return {} end
    lines = {}
    for line in io.lines(file) do
        if not (line == '') then
            lines[#lines + 1] = line
        end
    end
    return shuffle(lines)
end

--参数化商品
productIds = non_empty_lines_from("order_submitBuyNow.txt")
-- 参数化用户
userIds = non_empty_lines_from("user.txt")

users_len = #userIds

user_counter = 1

prod_counter = 1;

function response(status, headers, body)
    ---   print(status..body)
end

--[[function done(summary, latency, requests)
print("latency.min,latency.max,latency.mean,latency.stdev,latency:percentile(50.0),latency:percentile(90.0),latency:percentile(95.0),latency:percentile(99.0),summary.duration,summary.requests,summary.bytes,summary.errors.connect,summary.errors.read,summary.errors.write,summary.errors.status,summary.errors.timeout,qps,Transfer/sec(KB)")
print(latency.min/1000 .. "," .. latency.max/1000 .. "," .. latency.mean/1000 .. "," .. latency.stdev/1000 .. "," .. latency:percentile(50.0)/1000 .. "," .. latency:percentile(90.0)/1000 .. "," .. latency:percentile(95.0)/1000 .. "," .. latency:percentile(99.0)/1000 .. "," .. summary.duration/1000000 .. "," .. summary.requests .. "," .. summary.bytes .. "," .. summary.errors.connect.. "," .. summary.errors.read.. "," .. summary.errors.write.. "," .. summary.errors.status.. "," .. summary.errors.timeout .. "," .. summary.requests/(summary.duration/1000000) .. "," .. (summary.bytes/1024)/(summary.duration/1000000))
end]]

function request()

    productId = productIds[prod_counter]
    prod_counter = prod_counter + 1
    if prod_counter > #productIds then
        prod_counter = 1
    end

    userId = userIds[user_counter]
    user_counter = user_counter + 1
    if user_counter > #userIds then
        user_counter = 1
    end

    -- print("path: [" .. path .."]")



    -- productId=productIds[math.random(#productIds)];

    local body = '{"coupons": [],"shipCode": "003","userId":"' .. userId .. '","productId":"' .. productId .. '","addressId": " 00220171130132750215VGhPsroi06FD",  "productCount":1, "remark":"sdsdfffdsdsfd","imgCode":"108"}'
    --local body = '{"coupons": [],"shipCode": "003","userId":"bitmaintestsso47@bitmain.com","productId":"'..productId..'","addressId": " 00220171130132750215VGhPsroi06FD",  "productCount":1, "remark":"sdsdfffdsdsfd","imgCode":"108"}'

    --return wrk.format(wrk.method,wrk.path,wrk.headers,wrk.body)
    -- return wrk.format(wrk.method,path)
    return wrk.format(nil, nil, nil, body)
end


